# Aliases
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias ll='ls -lah'
alias la='ls -A'
alias l='ls -CF'
alias c='clear'
alias CH='ssh 208.85.0.1 -p 2222'
alias NULLR='ssh null-router.hivelocity.net'
alias dots='cd $HOME/.dots/'
alias work='tmuxinator start work'
alias works='tmuxinator stop work'
alias pystart='source ~/Documents/Scripts/.global_venv/bin/activate'
alias pystop='deactivate'
alias legacy-start='sudo docker start legacy-ssh'
alias legacy-connect='sudo docker exec -it legacy-ssh bash'
alias legacy-stop='sudo docker stop legacy-ssh'
alias serial='sudo picocom -b 9600 /dev/ttyUSB0'
