# ~/.bashrc
# Bach Master File

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Source additional config files if needed
for file in ~/.bashrc.d/*.sh; do
  [ -r "$file" ] && source "$file"
done

# 1Pass Socket
export SSH_AUTH_SOCK=$HOME/.1password/agent.sock

# Claude Code
export PATH="$HOME/.npm-global/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# Bash Auto Completion
if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
fi

# Prompt
PS1='\[\e[38;5;39m\]\[\e[1m\]\[\e[0m\] [\W]: '
