# ~/.bashrc
# Bash configuration file

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# TERM
export TERM=xterm-256color

# History settings
HISTCONTROL=ignoredups:erasedups
HISTSIZE=10000
HISTFILESIZE=20000
shopt -s histappend
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# Prompt
#PS1='[󰣇 \W]\$ '
PS1='[\[\e[38;5;39;1m\]󰣇\[\e[0m\] \W]$ '

# Aliases
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias ll='ls -lah'
alias la='ls -A'
alias l='ls -CF'

alias CH='ssh 208.85.0.1 -p 2222 -i $HOME/.ssh/id_ed25519_github'
alias dots='cd $HOME/.dotfiles/'

# Enable programmable completion features (if not already enabled)
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# Set PATH additions here
# export PATH="$HOME/bin:$PATH"

# SSH Keychain (Optional if using Keychain for SSH agent)
if command -v keychain &>/dev/null; then
    eval "$(keychain --quiet --eval id_ed25519_github)"
fi

# Source additional config files if needed
for file in ~/.bashrc.d/*.sh; do
    [ -r "$file" ] && source "$file"
done
